- name: ensure python-pip present
  pacman:
    name:
      - python-pip
      - python-virtualenv
      - python-fastnumbers
      - python-treelib
      - python-jack-client
      - tk
  become: yes

