- include_tasks: debian_based.yml
  when: ansible_os_family == "Debian"

- include_tasks: archlinux_based.yml
  when: ansible_os_family == "Archlinux"

- name: copy renardo lib
  synchronize:
    src: "{{ role_path }}/files/renardo_lib"
    dest: "/home/{{ ansible_user_id }}/bin"
  delegate_to: "localhost"

# - name: install renardo lib deps manually
#   pip:
#     name:
#       # - treelib # installed via pacman
#       # - fastnumbers # installed via pacman
#       - python-reapy
#       - playsound
#       - mido
#       # - jack-client # installed via pacman
#     virtualenv: /home/{{ ansible_user_id }}/bin/renardo_lib/venv

# - name: install renardo lib
#   pip:
#     name: '.'
#     chdir: /home/{{ ansible_user_id }}/bin/renardo_lib
#     editable: yes
#     virtualenv: /home/{{ ansible_user_id }}/bin/renardo_lib/venv

- name: Install deps via pip at user level without venv
  command: pip install python-reapy playsound mido --break-system-packages && touch /home/{{ ansible_user_id }}/bin/renardo_lib_deps.flag
  args:
    creates: /home/{{ ansible_user_id }}/bin/renardo_lib_deps.flag

- name: Install renardo via pip at user level without venv
  command: pip install -e . --break-system-packages && touch /home/{{ ansible_user_id }}/bin/renardo_lib.flag
  args:
    chdir: /home/{{ ansible_user_id }}/bin/renardo_lib
    creates: /home/{{ ansible_user_id }}/bin/renardo_lib.flag