- name: ensure user bin directory exists
  file:
    path: /home/{{ ansible_user_id }}/bin
    state: directory

- name: Download {{ application_name }}
  ansible.builtin.get_url:
    url: "{{ app_url }}"
    dest: "/home/{{ ansible_user_id }}/bin/{{ application_name }}.tar.xz"
    mode: 0644

- name: Uncompress reaper
  ansible.builtin.unarchive:
    src: "/home/{{ ansible_user_id }}/bin/{{ application_name }}.tar.xz"
    dest: "/home/{{ ansible_user_id }}/bin/"
    remote_src: yes

- name: Install Reaper by script
  shell: bash install-reaper.sh --install /opt --integrate-desktop
  args:
    chdir: /home/{{ ansible_user_id }}/bin/reaper_linux_x86_64/
    creates: /opt/REAPER
  become: yes
