- name: ensure user bin directory exists
  file:
    path: /home/{{ ansible_user_id }}/bin
    state: directory

- name: Download {{ application_name }}
  ansible.builtin.get_url:
    url: "{{ app_url }}"
    dest: "/home/{{ ansible_user_id }}/bin/{{ application_name }}.tar.xz"
    mode: 0644

- name: Uncompress reaper
  ansible.builtin.unarchive:
    src: "/home/{{ ansible_user_id }}/bin/{{ application_name }}.tar.xz"
    dest: "/home/{{ ansible_user_id }}/bin/"
    remote_src: yes