- name: register task to test if manjaro
  pacman:
    update_cache: yes
    name: manjaro-system
  become: yes
  ignore_errors: yes
  register: test_manjaro

- name: remove manjaro pulse & jack
  pacman:
    name:
      - manjaro-pulse
      - pulseaudio-zeroconf
      - pulseaudio-alsa
      - pulseaudio
      - pulseaudio-bluetooth
      - pulseaudio-ctl
      - jack2
    state: absent
    force: yes
    extra_args: --recursive
  become: yes
  when: not test_manjaro.failed

- name: install manjaro pipewire
  pacman:
    name:
      - wireplumber
      - manjaro-pipewire
      - pipewire-jack
      - bluez
      - bluez-utils
      - blueman
      # - pulseaudio-bluetooth
  become: yes
  when: not test_manjaro.failed