- include_tasks: debian_based.yml
  when: ansible_os_family == "Debian"

- include_tasks: archlinux_based.yml
  when: ansible_os_family == "Archlinux"

- name: Copy quarks to supercollider location
  synchronize:
    src: "{{ role_path }}/files/downloaded-quarks-provision/"
    dest: /home/{{ ansible_user_id }}/.local/share/SuperCollider/downloaded-quarks
  delegate_to: "localhost"